name: Update auto completion yaml

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      # Template change
      - "./autocompletion/templates/*.yaml"
      # GH change
      - ".github/workflows/update_autocompletion.yml"
      - ".github/scripts/update_autocompletion.sh"

jobs:
  update_autocompletion_yaml:
    name: update autocompletion yaml
    concurrency: git_commits
    runs-on: ubuntu-latest
    steps:
      # Standard checkout step
      - name: Checkout code
        id: git_checkout
        uses: actions/checkout@v4
      # Get Date
      - id: get_date
        name: Get Date
        shell: bash
        run: |
          echo "$(date +%Y%m%d)" >> "${GITHUB_OUTPUT}"
      # Run autocompletion script
      - id: update_autocompletion
        name: update autocompletion
        run: |
          docker run \
             --rm \
             --user "$(id -u):$(id -g)" \
             --volume  "$PWD:$PWD" \
             --workdir "$PWD" \
             --entrypoint "bash" \
             ghcr.io/alexiswl/app-appspec-p5:v0.007 \
               ".github/scripts/update_autocompletion.sh"
      # Commit to github
      - id: commit_configuration_yaml_files
        name: Commit configuration yaml files
        uses: EndBug/add-and-commit@v9.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add: "autocompletion/"
          default_author: github_actions
          message: "Updating autocompletion - (Autogenerated github actions commit)"
          push: true
          pull: ${{ format('--rebase --autostash origin {0}', github.event.pull_request.head.ref ) }}
          new_branch: ${{ format('autocompletion-update-{0}-{1}, steps.get_date.outputs.get_date, github.sha }}
